export const categories = [
  { name: 'Todo', icon: '✳', count: '124' },
  { name: 'Computadoras', icon: '▧', count: '38' },
  { name: 'Componentes', icon: '⌘', count: '26' },
  { name: 'Periféricos', icon: '⌁', count: '31' },
  { name: 'Monitores', icon: '▣', count: '18' },
  { name: 'Audio', icon: '◖', count: '11' },
]

export const offers = [
  {
    id: 1,
    name: 'Logitech G305 Lightspeed',
    subtitle: 'Mouse inalámbrico · 12.000 DPI',
    category: 'Periféricos',
    price: 18900,
    oldPrice: 24900,
    store: 'Faith Technology',
    initials: 'FT',
    storeColor: '#e9f3ed',
    storeText: '#265940',
    badge: 'Mejor precio',
    badgeType: 'best',
    image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=85',
    alt: 'Mouse inalámbrico negro sobre fondo oscuro',
    trend: '12% menos que el promedio',
    rating: '4.8',
    reviews: '128',
    featured: true,
  },
  {
    id: 2,
    name: 'Logitech G305 Lightspeed',
    subtitle: 'Mouse inalámbrico · Negro',
    category: 'Periféricos',
    price: 21500,
    store: 'Intelec',
    initials: 'in',
    storeColor: '#f0f0e7',
    storeText: '#676b45',
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=85',
    alt: 'Mouse gamer sobre escritorio',
    rating: '4.7',
    reviews: '86',
  },
  {
    id: 3,
    name: 'Logitech G305 Lightspeed',
    subtitle: 'Mouse inalámbrico · Blanco',
    category: 'Periféricos',
    price: 23900,
    oldPrice: 27900,
    store: 'ExtremeTech',
    initials: 'XT',
    storeColor: '#f8ece7',
    storeText: '#9c5036',
    badge: 'Envío gratis',
    badgeType: 'shipping',
    image: 'https://images.unsplash.com/photo-1613141412501-9012977f1969?auto=format&fit=crop&w=900&q=85',
    alt: 'Mouse blanco sobre una mesa clara',
    rating: '4.6',
    reviews: '54',
  },
  {
    id: 4,
    name: 'Logitech G305 Lightspeed',
    subtitle: 'Mouse inalámbrico · Negro',
    category: 'Periféricos',
    price: 25900,
    store: 'Walmart Costa Rica',
    initials: 'W',
    storeColor: '#e9eef8',
    storeText: '#3157a4',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=85',
    alt: 'Mouse negro visto desde arriba',
    rating: '4.5',
    reviews: '212',
  },
]

export const trendingSearches = [
  { label: 'RTX 5060', icon: '▦' },
  { label: 'MacBook Air M4', icon: '▱' },
  { label: 'Logitech G305', icon: '⌁' },
]

export const formatPrice = (price, currency = 'CRC') => new Intl.NumberFormat(currency === 'USD' ? 'en-US' : 'es-CR', {
  style: 'currency',
  currency,
  maximumFractionDigits: currency === 'USD' ? 2 : 0,
}).format(price)
