export const offers = [
  {
    id: 1,
    name: 'Logitech G305 Lightspeed',
    subtitle: 'Mouse inalámbrico · 12.000 DPI',
    category: 'Periféricos',
    price: 18900,
    oldPrice: 24900,
    store: 'Faith Technology',
    initials: 'FT',
    storeColor: '#e9f3ed',
    storeText: '#265940',
    badge: 'Mejor precio',
    badgeType: 'best',
    image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=85',
    alt: 'Mouse inalámbrico negro sobre fondo oscuro',
    trend: '12% menos que el promedio',
    rating: '4.8',
    reviews: '128',
    featured: true,
  },
  {
    id: 2,
    name: 'Logitech G305 Lightspeed',
    subtitle: 'Mouse inalámbrico · Negro',
    category: 'Periféricos',
    price: 21500,
    store: 'Intelec',
    initials: 'in',
    storeColor: '#f0f0e7',
    storeText: '#676b45',
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=85',
    alt: 'Mouse gamer sobre escritorio',
    rating: '4.7',
    reviews: '86',
  },
  {
    id: 3,
    name: 'Logitech G305 Lightspeed',
    subtitle: 'Mouse inalámbrico · Negro',
    category: 'Periféricos',
    price: 25900,
    store: 'Walmart Costa Rica',
    initials: 'W',
    storeColor: '#e9eef8',
    storeText: '#3157a4',
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=85',
    alt: 'Mouse negro visto desde arriba',
    rating: '4.5',
    reviews: '212',
  },
]

export const formatPrice = (price, currency = 'CRC') => new Intl.NumberFormat(currency === 'USD' ? 'en-US' : 'es-CR', {
  style: 'currency',
  currency,
  maximumFractionDigits: currency === 'USD' ? 2 : 0,
}).format(price)
